repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: mixed-line-ending

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length=100]
        files: '(^neurocaps/.*\.py$|.*^tests.*\.py$|^demos/.*\.ipynb$)'
        additional_dependencies:
        - black[jupyter]

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs
        args: [--line-length=100]
        additional_dependencies:
        - black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
        - id: ruff
          # Ensure no print statements are in the codebase; only logging allowed
          entry: ruff check --select T201
          files: '(^neurocaps/.*\.py$|.*^tests.*\.py$)'
          exclude: '(test_TimeseriesExtractor.py$|test_CAP.py$)'

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [pre-push]
        types: [python]
        entry: python -m pytest
        language: system
        always_run: true

-   repo: local
    hooks:
    -   id: grep
        name: grep
        # Public classes the underscore prefix for attribute names. These attributes are accessed using private getter
        # classes which allows access to these attributes via properties.
        description: Uses grep to ensure all attributes in the TimeseriesExtractor and CAP classes have the underscore prefix
        types: [python]
        entry: python hooks/grep.py
        language: system
