repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: mixed-line-ending

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: [--line-length=120]
        files: '(^neurocaps/.*\.py$|.*^tests.*\.py$)'

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [pre-push]
        types: [python]
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: false
