---
name: Documentation

description: Template to suggest documentation improvement.

title: '[DOC]'

labels: [documentation]

body:

-   type: textarea
    attributes:
        label: Issue with Current Documentation
        description: Explain what's unclear, missing, or needs improvement in the existing documentation.
    validations:
        required: true

-   type: textarea
    attributes:
        label: Suggested Improvement
        description: Describe your proposed changes or additions to the documentation.
    validations:
        required: true
