name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-ver: ['3.9', '3.12']

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install Packages
        run: |
          pip install asv 'virtualenv<20.31.0'

      - name: Run benchmarks in virtual environment; skip if submodule changed or
              compare current commit with previous commit if submodule is the same
        run: |
          asv machine --yes
          if ! git diff --quiet HEAD~1 HEAD -- tests/data; then
            echo "Submodule changed may result in breaking change; skipping run"
          else
            asv continuous HEAD~1 HEAD
          fi
        shell: bash
