name: Test Minimum Dependencies

on:
  push:
    branches: [main, development]
  pull_request:
    branches:
      - '*'

jobs:
  test-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-ver: ['3.9']

    name: Python ${{ matrix.python-ver }} check on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install packages
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          pip install -r requirements.txt
        working-directory: tests/minimum_dependencies

      - name: Install package & pytest for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --system core.longpaths true
          pip install -r requirements.txt
        working-directory: tests/minimum_dependencies

      - name: Install NeuroCAPs
        run: pip install .[test]

      - name: Run tests with Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coactions/setup-xvfb@v1
        with:
          options: -screen 0 1600x1200x24
          run: |
            pytest .

      - name: Run test for Mac & Windows
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: |
          pytest .
        working-directory: tests
