name: Pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '*'

jobs:
  precommit:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install precommit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run precommit
        run: |
          pre-commit run --all-files
